App\Entity\Tree:
  type: entity
  table: trees
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  oneToOne:
    rootUser:
      targetEntity: UserLeaf
      joinColumn:
        name: rootUser_id
        referencedColumnName: id
      nullable: true
      cascade: ["persist"]
