App\Entity\UserLeaf:
  type: entity
  table: user_leaves
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    username:
      type: string
      length: 250
    leftCredits:
      type: integer
    rightCredits:
      type: integer
  oneToOne:
    leftLeaf:
      targetEntity: UserLeaf
      joinColumn:
        name: left_leaf_id
        referencedColumnName: id
      nullable: true
      cascade: ["persist"]
    rightLeaf:
      targetEntity: UserLeaf
      joinColumn:
        name: right_leaf_id
        referencedColumnName: id
      nullable: true
      cascade: ["persist"]
